Book.create(title: "Ouran High School Host Club", volume: 1)
Book.create(title: "Sekaiichi Hatsukoi", volume: 2)
Book.create(title: "Sekaiichi Hatsukoi", volume: 1)
Book.create(title: "Sekaiichi Hatsukoi", volume: 3)
Book.create(title: "Junjou Romantica", volume: 1)
Book.create(title: "Boku no Hero Academia", volume: 1)
Author.create(name: "Bisco Hatori")
Author.create(name: "Shungiku Nakamura")
Author.create(name: "Horikoshi Kouhei")
Genre.create(name: "shounen")
Genre.create(name: "yaoi")
Genre.create(name: "shoujo")
Genre.create(name: "shounen ai")
